### ISSUE TITLE
Sublime3 is crashing after adding meteor.js into TermJS plugin forlder

### ISSUE THREAD

**Issue by chompomonim** [Slava/tern-meteor#11]
I just added meteor.js into TermJS/termjs/plugins frolder. Then I opened edit project and  added there:
"ternjs": {
        "libs": ["browser", "underscore", "jquery"],
        "plugins": {
          "meteor": {}
        }
      }

Finally I started to type and my Sublime Text 3 started to slowdown after typing first letter. Finally it become unresponsive and all system become so slow too.

**Comment by Slava** [comment]
I don't know if this is still an issue, but please try out my new stand-alone package for ST3 that doesn't require any configuration: https://github.com/Slava/tern-meteor-sublime
