### ISSUE TITLE
Python issues with TernJS plugin

### ISSUE THREAD

**Issue by vbezruchkin** [Slava/tern-meteor#24]
Hi Slava,

I do understand it's more a TernJS issue, so I have posted the details in their official repository: emmetio/sublime-tern#42

Anyway, I'd better duplicate my question here. Have you ever met an error similar to mine before and what was the solution for it? 

I want to use ST3 for meteor development as phpStorm does not work well with shared vagrant boxes.

Thanks

P.S. cheers from Бишкек, Кыргызстан )

**Comment by Slava** [comment]
I released a stand-alone package for Sublime that should work well: https://github.com/Slava/tern-meteor-sublime
