### ISSUE TITLE
Error loading meteor plugin

### ISSUE THREAD

**Issue by topazas** [Slava/tern-meteor#28]
Hi, 

in ubuntu 14.04 SublimeText 3 cloned meteor.js into TernJS plugin dir. My config is like this:

```
      "ternjs": {
        "libs": ["browser", "underscore", "jquery"],
        "exclude": [".meteor/**", "node_modules/**"],
        "plugins": {
        	/* "meteor": {} */
        }
      }
```

After uncommeting meteor, sublime crashes with message:

```
Starting TernJS server for /home/myuser/meteor/simple-todos/todo.sublime-project with 4 libs and 1 files
resource not found
error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted
```

Any suggestions?

**Comment by Slava** [comment]
I would recommend to switch to my new package for Sublime that bundles everything nicely w/o any extra configuration: https://github.com/Slava/tern-meteor-sublime
