### ISSUE TITLE
Atom support?

### ISSUE THREAD

**Issue by travischoma** [Slava/tern-meteor#37]
I have Ternjs installed in Atom, is there any path to running tern-meteor on Atom?

**Comment by newswim** [comment]
Also curious on this, it seems Sublime integration has internal process issues and I've been slowly adopting Atom.

**Comment by Slava** [comment]
I think it is described in the readme. Copy the Meteor.js file from this repo into the plugins folder of your tern installation and then enable it in your .tern-project file.

**Comment by angelozerr** [comment]
IMHO, I think tern-meteor should be published in the npm registry like other tern plugins https://www.npmjs.com/search?q=tern

So after user could install it with npm install (see for instance https://www.npmjs.com/package/tern-tabris#installation)

I had created a PR for that https://github.com/Slava/tern-meteor/pull/17

**Comment by Slava** [comment]
If you guys want to maintain a copy on npm, I have no problems with that, you are free to do this. Closing this issue as it is not a bug.

**Comment by ferhtgoldaraz** [comment]
I've published a fork of this on npm. Anything I should know, tell me.
