### ISSUE TITLE
Installation into Linux Sublime Text 3

### ISSUE THREAD

**Issue by pnunn** [Slava/tern-meteor#7]
Hi, I'm trying to follow the bouncing ball with Sublime Text 3 on Linux. I've installed the tern packages (both of them) using the package manager, but can find no trace of the location to put the .js file. Doing a search, the only mention of tern on the system is in ~/.config/sublime-text-3/Installed Packages but that is a binary package.

Ta.

Peter.

**Comment by Slava** [comment]
Try my new package that doesn't require any configuration: https://github.com/Slava/tern-meteor-sublime
